### ISSUE TITLE
emscripten_asm_const_int_sync_on_main_thread is undefined

### ISSUE THREAD

**Issue by vikram-kangotra** [ALEX11BR/emscripten-functions#1]
**Description:**
After the bindgen emits this function and outputs the translated code to Rust, the function `emscripten_asm_const_int_sync_on_main_thread` is found in the file `emscripten-functions-sys/src/emscripten.rs`. However, when called, it says the function is undefined.

**Steps to Reproduce:**
- Call the code in Rust as follows:

```rust
unsafe {
    emscripten_functions_sys::emscripten::emscripten_asm_const_int_sync_on_main_thread("console.log('hello');".as_ptr() as *const i8, "ii\0".as_ptr() as *const i8, 1, 2);
}
```

**Working code in C**:
- If the code is written in C as follows:

```c
MAIN_THREAD_EM_ASM(
    console.log("Hello from the main thread !", $0);
, 12);
```

- Expand the `MAIN_THREAD_EM_ASM` macro and get something like this:

```c
((void)emscripten_asm_const_int_sync_on_main_thread((__extension__({ __attribute__((section("em_asm"), aligned(1))) static const char x[] = "console.log(\"Hello from the main thread !\", $0);"; x; })) , ((char[]){ _Generic((12), float: 'f', double: 'd', long long: 'j', default: 'i'), '\0' }),12));
```

- The above code works but if you change the section to anything else, you get the same error as:

```
error: undefined symbol: emscripten_asm_const_int_sync_on_main_thread (referenced by root reference (e.g. compiled C/C++ code ))
warning: To disable errors for undefined symbols use `-sERROR_ON_UNDEFINED_SYMBOLS=0`
warning: _emscripten_asm_const_int_sync_on_main_thread may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
emcc: error: '/usr/bin/node /usr/lib/emscripten/src/compiler.js /tmp/tmps0cj3_do.json' failed (returned 1)
```

- Found that the parameters need to be given in a specific way. In C/C++, it's done using the macro `CODE_EXPR` defined as:

```c
#define CODE_EXPR(code) (__extension__({           \
    __attribute__((section("em_asm"), aligned(1))) \
    static const char x[] = code;                  \
    x;                                             \
  }))
```

- The first argument should be the result of `CODE_EXPR(code)`, and the second one should be using `_EM_ASM_PREP_ARGS(__VA_ARGS__)`. This works as an example given below:

```c
_EM_ASM_PREP_ARGS(12)
```

- The output would be:

```
, ((char[]){ _Generic((12), float: 'f', double: 'd', long long: 'j', default: 'i'), '\0' }),12
```

- Which is same as

```
, "i", 12
```

**Expected Result:**
The function `emscripten_asm_const_int_sync_on_main_thread` should not be undefined, and the code should compile successfully.

I have been trying to solve this issue for a long time. Any help or guidance on how to solve it would be greatly appreciated.

**Comment by ALEX11BR** [comment]
Hello, and thank you for your interest and detailed report!

#### My notes:

I tried running your proposed rust code (probably you forgot a final `\0` in the script argument so I tweaked it):
```rust
unsafe {
    emscripten_functions_sys::emscripten::emscripten_asm_const_int_sync_on_main_thread("console.log('hello');\0".as_ptr() as *const i8, "ii\0".as_ptr() as *const i8, 1, 2);
}

```
and it compiled successfully and running it gave me an error in the web console:
```
> Aborted(No EM_ASM constant found at address 66899)
> Uncaught RuntimeError: Aborted(No EM_ASM constant found at address 66899)
    at abort (PROJECT.js:669:11)
    at runMainThreadEmAsm (PROJECT.js:5398:45)
    at _emscripten_asm_const_int_sync_on_main_thread (PROJECT.js:5402:14)
    at THE_FUNCTION_THAT_WAS_RUNNING_THE_CODE (PROJECT.wasm:0xdae1)
    etc ...
```

I found that `runMainThreadEmAsm` looks like this:
```js
  var runMainThreadEmAsm = (code, sigPtr, argbuf, sync) => {
      var args = readEmAsmArgs(sigPtr, argbuf);
      if (!ASM_CONSTS.hasOwnProperty(code)) abort(`No EM_ASM constant found at address ${code}`);
      return ASM_CONSTS[code].apply(null, args);
    };
```
where `code` is the pointer with the code string. Now `ASM_CONSTS` looks like:
```js
var ASM_CONSTS = {
  159768: ($0) => { var str = UTF8ToString($0) + '\n\n' + 'Abort/Retry/Ignore/AlwaysIgnore? [ariA] :'; var reply = window.prompt(str, "i"); if (reply === null) { reply = "i"; } return allocate(intArrayFromString(reply), 'i8', ALLOC_NORMAL); },  
 159993: () => { if (typeof(AudioContext) !== 'undefined') { return true; } else if (typeof(webkitAudioContext) !== 'undefined') { return true; } return false; },  
// etc ...
```
so basically some JS functions mapped to some addresses of the WASM address space, I guess.
Probably the sections the code gets put in makes the compiler add it to `ASM_CONSTS` or whatever.

As I didn't bother to implement the [`EM_ASM`](https://emscripten.org/docs/api_reference/emscripten.h.html#c.EM_ASM) macros, but rather used the [`emscripten_run_script`](https://emscripten.org/docs/api_reference/emscripten.h.html#c.emscripten_run_script) functions, its main thread equivalent seems to be `emscripten_sync_run_in_main_runtime_thread` (this is what the docs say), which lives in the `emscripten/threading.h` header which I have not ported (it wasn't listed in the emscripten API reference as one with documented functions). It has this signature:
```c
void emscripten_async_run_in_main_runtime_thread_(EM_FUNC_SIGNATURE sig, void *func_ptr __attribute__((nonnull)), ...);
```
and needs the compile and link `-pthread` flag to work. I have no idea what its args mean.

#### Takeaway:
To add the possibility to run user JS in the main thread, probably the easiest solution would be to write some C code like:
```c
void run_in_main_thread(char *script) {
    MAIN_THREAD_EM_ASM("eval(UTF8ToString($0))", script);
}
```
to compile, like, with `CC` in `build.rs` and FFI with it.

I plan to add (about tomorrow) something like this to the `emscripten-functions` library.

**Comment by vikram-kangotra** [comment]
Hi, Thanks for the quick response 

> ```rust
> unsafe {
>     emscripten_functions_sys::emscripten::emscripten_asm_const_int_sync_on_main_thread("console.log('hello');\0".as_ptr() as *const i8, "ii\0".as_ptr() as *const i8, 1, 2);
> }
> ```
> 
> and it compiled successfully and running it gave me an error in the web console:
> 

Ah, I know this. It seems to be kind of weird behavior to me but it compiled only because you must already be using `MAIN_THREAD_EM_ASM` in some C/C++ file or somewhere. Remove from there and It won't even compile now.

> #### Takeaway:
> To add the possibility to run user JS in the main thread, probably the easiest solution would be to write some C code like:
> 
> ```c
> void run_in_main_thread(char *script) {
>     MAIN_THREAD_EM_ASM("eval(UTF8ToString($0))", script);
> }
> ```
> 
> to compile, like, with `CC` in `build.rs` and FFI with it.

I'm currently doing the same, but I need to retrieve data from the JavaScript side. Is there another way to do this?

**Comment by ALEX11BR** [comment]
I added the `run_script_main_thread` family of functions to `emscripten-functions`, based on the C solution proposed above.

#### Discussion

> I need to retrieve data from the JavaScript side. Is there another way to do this?

Some proposals:
* Use [`sessionStorage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) or something similar - note that you'll have to return a C string pointer, emscripten's JS [`stringToUTF8`](https://emscripten.org/docs/api_reference/preamble.js.html#stringToUTF8) works on a already allocated limited size pointer; the bytes length of the string can be computed.
* Make using [`addFunction`](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#calling-javascript-functions-as-function-pointers-from-c) some function pointers that return your requested data and pass them to the function that you run in the thread and needs to get them from time to time or however you organized your code.
* Use a method of transmitting the JS data that works in [web workers](https://developer.mozilla.org/en-US/docs/Web/API/Worker), so that you can use the according `run_script` function in your thread.
* If you don't call `std::thread::spawn` or whatever, you are in the main thread, and you can use the according `run_script` function and have it run in the main thread and access sessionStorage or whatever.

**Comment by vikram-kangotra** [comment]
Thanks for the suggestion :)

I found why my approach was not working. I was using this code:

```rust
macro_rules! CODE_EXPR {
    ($code:expr) => {{
        lazy_static! {
            #[link_section = "em_asm"]
            static ref X: [u8; $code.len()] = $code.as_bytes().try_into().unwrap();
        }
        X.as_ptr() as *const i8
    }};
}
```
Which I mistakenly thought would write the string to `em_asm` data section. But as I found [here](https://github.com/emscripten-core/emscripten/issues/13838), this is not true. Instead in rust, using the `wasm` target, the `link_section` writes to custom section (used for `wasm-bindgen`). 

So this can't be fixed from our end until things changes from either the rust's side or the emscripten's side (will be working on it). So closing this issue.

Thanks again for the help :)
